BRANCHES = [
    {"id": "branch-north", "name": "Sede Norte"},
    {"id": "branch-center", "name": "Sede Centro"},
]

BOOKS = [
    {
        "id": "book-001",
        "title": "El Archivo de las Tormentas",
        "author": "Brandon Sanderson",
        "genre": "fantasia",
        "price": 92000,
        "description": "Novela de fantasia epica con mundos extensos y conflictos politicos.",
        "available": True,
        "stockByBranch": {"branch-north": 4, "branch-center": 2},
    },
    {
        "id": "book-002",
        "title": "La Ciudad de los Libros Perdidos",
        "author": "Marina Rios",
        "genre": "fantasia",
        "price": 58000,
        "description": "Aventura fantastica sobre bibliotecas secretas y mapas imposibles.",
        "available": True,
        "stockByBranch": {"branch-north": 1, "branch-center": 0},
    },
    {
        "id": "book-003",
        "title": "Python Practico",
        "author": "Laura Mendez",
        "genre": "programacion",
        "price": 75000,
        "description": "Guia practica para construir aplicaciones con Python moderno.",
        "available": True,
        "stockByBranch": {"branch-north": 6, "branch-center": 3},
    },
    {
        "id": "book-004",
        "title": "Arquitectura Limpia para APIs",
        "author": "Diego Salazar",
        "genre": "software",
        "price": 81000,
        "description": "Patrones para disenar APIs mantenibles y bien separadas.",
        "available": True,
        "stockByBranch": {"branch-north": 2, "branch-center": 2},
    },
    {
        "id": "book-005",
        "title": "Historia Breve de la Lectura",
        "author": "Clara Nieto",
        "genre": "historia",
        "price": 45000,
        "description": "Recorrido historico por los habitos de lectura y bibliotecas.",
        "available": False,
        "stockByBranch": {"branch-north": 0, "branch-center": 0},
    },
    {
        "id": "book-006",
        "title": "Matilda",
        "author": "Roald Dahl",
        "genre": "infantil",
        "price": 39000,
        "description": "Historia infantil para ninos y lectores de libros infantiles sobre una nina brillante, libros y valentia.",
        "available": True,
        "stockByBranch": {"branch-north": 5, "branch-center": 4},
    },
    {
        "id": "book-007",
        "title": "El Hobbit",
        "author": "J. R. R. Tolkien",
        "genre": "fantasia",
        "price": 50000,
        "description": "Aventura fantastica de Bilbo Bolson hacia la Montana Solitaria.",
        "available": True,
        "stockByBranch": {"branch-north": 3, "branch-center": 2},
    },
    {
        "id": "book-008",
        "title": "Harry Potter y la piedra filosofal",
        "author": "J. K. Rowling",
        "genre": "fantasia",
        "price": 54000,
        "description": "Inicio de una saga de magia, amistad y misterio.",
        "available": True,
        "stockByBranch": {"branch-north": 4, "branch-center": 1},
    },
    {
        "id": "book-009",
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "genre": "programacion",
        "price": 88000,
        "description": "Buenas practicas para escribir codigo mantenible.",
        "available": True,
        "stockByBranch": {"branch-north": 2, "branch-center": 1},
    },
    {
        "id": "book-010",
        "title": "Alicia en el pais de las maravillas",
        "author": "Lewis Carroll",
        "genre": "fantasia",
        "price": 42000,
        "description": "Clasico fantastico sobre curiosidad, imaginacion y mundos imposibles.",
        "available": True,
        "stockByBranch": {"branch-north": 2, "branch-center": 2},
    },
    {
        "id": "book-011",
        "title": "El Senor de los Anillos",
        "author": "J. R. R. Tolkien",
        "genre": "fantasia",
        "price": 99000,
        "description": "Epopeya fantastica sobre la Comunidad del Anillo.",
        "available": True,
        "stockByBranch": {"branch-north": 1, "branch-center": 1},
    },
]

SALES = [
    {
        "id": "sale-001",
        "sessionId": "session-demo",
        "originCode": "CHATBOT",
        "status": "MOCK_ONLY",
        "total": 92000,
        "items": [{"bookId": "book-001", "quantity": 1, "unitPrice": 92000}],
        "invoiceId": "FAC-0001",
    }
]

INVOICES = [
    {
        "id": "FAC-0001",
        "saleId": "sale-001",
        "total": 92000,
        "status": "MOCK_ONLY",
        "issuedAt": "2026-07-06T12:00:00Z",
    }
]
