namespace Infrastructure.Persistence.SeedData;

public static class CategoryTaxonomySeedData
{
    public static IReadOnlyCollection<string> CategoryNames { get; } =
    [
        "Ficción",
        "No ficción",
        "Infantil",
        "Juvenil",
        "Académicos",
        "Cómic y novela gráfica",
        "Poesía",
        "Teatro",
        "Audiolibros",
        "Religión",
        "Arte",
        "Cocina",
        "Viajes",
        "Salud",
        "Tecnología",
        "Negocios",
        "Idiomas",
        "Bolsillo",
        "Coleccionables",
        "Ediciones especiales",
        "Fantasía épica",
        "Fantasía urbana",
        "Ciencia ficción",
        "Distopía",
        "Romance",
        "Romántica juvenil",
        "Terror",
        "Misterio",
        "Thriller",
        "Novela negra",
        "Histórica",
        "Aventura",
        "Realismo mágico",
        "Contemporánea",
        "Dark romance",
        "Biografías",
        "Autobiografías",
        "Historia",
        "Filosofía",
        "Ensayo",
        "Autoayuda",
        "Psicología",
        "Finanzas personales",
        "Emprendimiento",
        "Marketing",
        "Productividad",
        "Ciencia",
        "Tecnología",
        "Programación",
        "Liderazgo",
        "Primeras lecturas",
        "Cuentos ilustrados",
        "Aprendizaje temprano",
        "Actividades",
        "Colorear",
        "Juvenil fantasy",
        "Juvenil romance",
        "Juvenil aventura",
        "Matemáticas",
        "Física",
        "Química",
        "Biología",
        "Derecho",
        "Medicina",
        "Economía",
        "Administración",
        "Ingeniería",
        "Informática",
        "Lenguas",
    ];

    public static IReadOnlyCollection<(string OldName, string NewName)> CategoryRenames { get; } =
    [
        ("Libros religiosos", "Religión"),
        ("Libros de arte", "Arte"),
        ("Libros de cocina", "Cocina"),
        ("Libros de viajes", "Viajes"),
        ("Libros de salud", "Salud"),
        ("Libros de tecnología", "Tecnología"),
        ("Libros de negocios", "Negocios"),
        ("Libros de idiomas", "Idiomas"),
        ("Libros de bolsillo", "Bolsillo"),
    ];
}
