using System;
using System.Collections.Generic;
using System.Linq;

namespace Infrastructure.Persistence.SeedData;

public static class RealCatalogSeedData
{
    public static IReadOnlyCollection<string> Categories { get; } =
    [
        "Literatura clásica",
        "Literatura latinoamericana",
        "Novela contemporánea",
        "Fantasía",
        "Ciencia ficción",
        "Misterio",
        "Thriller",
        "Terror",
        "Filosofía",
        "Historia",
        "Sociedad",
        "Psicología",
        "Desarrollo personal",
        "Tecnología",
        "Programación",
        "Ingeniería de software",
        "Infantil",
        "Juvenil",
        "Educación",
        "Ciencia",
        "Biografía",
        "Feminismo",
        "Política",
        "Aventura",
        "Romance",
        "Distopía",
        "Ensayo",
        "Algoritmos",
        "Arquitectura de software",
        "Relato",
        "Realismo mágico"
    ];

    public static IReadOnlyCollection<string> Publishers { get; } =
    [
        "Penguin Classics",
        "Penguin Random House",
        "Debolsillo",
        "Alfaguara",
        "Planeta",
        "Seix Barral",
        "Anagrama",
        "Alianza Editorial",
        "Austral",
        "Cátedra",
        "Minotauro",
        "Salamandra",
        "Ediciones B",
        "HarperCollins",
        "Vintage",
        "Bloomsbury",
        "Tor Books",
        "Gollancz",
        "Ace Books",
        "Bantam Books",
        "O'Reilly Media",
        "Addison-Wesley",
        "Prentice Hall",
        "MIT Press",
        "No Starch Press",
        "Pearson",
        "McGraw-Hill"
    ];

    public static IReadOnlyCollection<RealCatalogBookSeed> Books { get; } =
    [
        new("Don Quijote de la Mancha", ["Miguel de Cervantes"], ["Literatura clásica", "Aventura"], "Cátedra", 1605, "Español", 45000m, "Novela de aventuras y sátira sobre idealismo, lectura y realidad en la España del Siglo de Oro."),
        new("Cien años de soledad", ["Gabriel García Márquez"], ["Literatura latinoamericana", "Realismo mágico"], "Alfaguara", 1967, "Español", 68000m, "Saga familiar que explora memoria, poder y soledad en el pueblo ficticio de Macondo."),
        new("La Odisea", ["Homero"], ["Literatura clásica", "Aventura"], "Penguin Classics", null, "Español", 39000m, "Poema épico sobre el regreso de Odiseo y las pruebas que enfrenta tras la guerra de Troya."),
        new("La Ilíada", ["Homero"], ["Literatura clásica", "Historia"], "Penguin Classics", null, "Español", 39000m, "Poema épico centrado en la guerra de Troya, el honor guerrero y la fragilidad humana."),
        new("Orgullo y prejuicio", ["Jane Austen"], ["Literatura clásica", "Romance"], "Penguin Classics", 1813, "Español", 42000m, "Novela social sobre amor, clase, prejuicios familiares y decisiones personales."),
        new("Crimen y castigo", ["Fiódor Dostoyevski"], ["Literatura clásica", "Psicología"], "Alianza Editorial", 1866, "Español", 52000m, "Relato psicológico sobre culpa, pobreza y redención tras un crimen cometido por un estudiante."),
        new("Madame Bovary", ["Gustave Flaubert"], ["Literatura clásica", "Novela contemporánea"], "Cátedra", 1857, "Español", 48000m, "Novela sobre deseo, frustración y choque entre fantasía romántica y vida cotidiana."),
        new("Moby Dick", ["Herman Melville"], ["Literatura clásica", "Aventura"], "Penguin Classics", 1851, "Español", 56000m, "Historia marítima sobre obsesión, destino y la persecución de una ballena blanca."),
        new("Los miserables", ["Victor Hugo"], ["Literatura clásica", "Historia"], "Penguin Classics", 1862, "Español", 62000m, "Novela amplia sobre justicia, pobreza, revolución y búsqueda de dignidad."),
        new("El retrato de Dorian Gray", ["Oscar Wilde"], ["Literatura clásica", "Terror"], "Austral", 1890, "Español", 43000m, "Fábula moral sobre belleza, corrupción y las consecuencias de una vida sin responsabilidad."),
        new("Anna Karenina", ["León Tolstói"], ["Literatura clásica", "Romance"], "Penguin Classics", 1877, "Español", 62000m, "Novela sobre pasión, familia y normas sociales en la Rusia del siglo XIX."),
        new("La metamorfosis", ["Franz Kafka"], ["Literatura clásica", "Relato"], "Alianza Editorial", 1915, "Español", 32000m, "Relato sobre alienación familiar y laboral a partir de una transformación inexplicable."),
        new("Grandes esperanzas", ["Charles Dickens"], ["Literatura clásica", "Novela contemporánea"], "Penguin Classics", 1861, "Español", 52000m, "Novela de formación sobre ambición, clase social y aprendizaje moral."),
        new("Jane Eyre", ["Charlotte Brontë"], ["Literatura clásica", "Romance"], "Penguin Classics", 1847, "Español", 47000m, "Historia de independencia emocional, educación y amor desde la voz de una protagonista decidida."),
        new("Cumbres borrascosas", ["Emily Brontë"], ["Literatura clásica", "Romance"], "Austral", 1847, "Español", 47000m, "Novela intensa sobre amor, resentimiento y vínculos familiares marcados por la obsesión."),
        new("Pedro Páramo", ["Juan Rulfo"], ["Literatura latinoamericana", "Realismo mágico"], "Planeta", 1955, "Español", 45000m, "Novela breve donde voces de vivos y muertos revelan la historia de un pueblo abandonado."),
        new("Rayuela", ["Julio Cortázar"], ["Literatura latinoamericana", "Novela contemporánea"], "Alfaguara", 1963, "Español", 69000m, "Novela experimental sobre búsqueda existencial, amor y lectura no lineal."),
        new("La ciudad y los perros", ["Mario Vargas Llosa"], ["Literatura latinoamericana", "Sociedad"], "Alfaguara", 1963, "Español", 58000m, "Retrato crítico de violencia, disciplina y poder dentro de un colegio militar."),
        new("El amor en los tiempos del cólera", ["Gabriel García Márquez"], ["Literatura latinoamericana", "Romance"], "Penguin Random House", 1985, "Español", 64000m, "Historia de un amor persistente atravesado por el tiempo, la memoria y la espera."),
        new("Ficciones", ["Jorge Luis Borges"], ["Literatura latinoamericana", "Relato"], "Debolsillo", 1944, "Español", 42000m, "Colección de relatos sobre laberintos, libros imaginarios, identidad y paradojas intelectuales."),
        new("La casa de los espíritus", ["Isabel Allende"], ["Literatura latinoamericana", "Realismo mágico"], "Debolsillo", 1982, "Español", 58000m, "Saga familiar marcada por política, memoria y elementos sobrenaturales."),
        new("Como agua para chocolate", ["Laura Esquivel"], ["Literatura latinoamericana", "Romance"], "Planeta", 1989, "Español", 48000m, "Novela donde cocina, tradición familiar y deseo se mezclan con realismo mágico."),
        new("El túnel", ["Ernesto Sabato"], ["Literatura latinoamericana", "Psicología"], "Seix Barral", 1948, "Español", 39000m, "Narración introspectiva sobre obsesión, aislamiento y una confesión criminal."),
        new("Los detectives salvajes", ["Roberto Bolaño"], ["Literatura latinoamericana", "Novela contemporánea"], "Anagrama", 1998, "Español", 78000m, "Novela coral sobre poetas, viajes, juventud y búsqueda literaria."),
        new("La tregua", ["Mario Benedetti"], ["Literatura latinoamericana", "Romance"], "Debolsillo", 1960, "Español", 41000m, "Diario íntimo sobre rutina, madurez y una relación que transforma una vida gris."),
        new("Doña Bárbara", ["Rómulo Gallegos"], ["Literatura latinoamericana", "Sociedad"], "Cátedra", 1929, "Español", 44000m, "Novela sobre civilización, poder rural y conflicto social en los llanos venezolanos."),
        new("El Hobbit", ["J. R. R. Tolkien"], ["Fantasía", "Aventura"], "Minotauro", 1937, "Español", 65000m, "Aventura fantástica sobre un viaje inesperado, tesoros antiguos y crecimiento personal."),
        new("El Señor de los Anillos", ["J. R. R. Tolkien"], ["Fantasía", "Aventura"], "Minotauro", 1954, "Español", 115000m, "Épica fantástica sobre amistad, poder y resistencia frente a una amenaza oscura."),
        new("Harry Potter y la piedra filosofal", ["J. K. Rowling"], ["Fantasía", "Juvenil"], "Salamandra", 1997, "Español", 62000m, "Inicio de una saga juvenil sobre magia, amistad y descubrimiento de identidad."),
        new("El nombre del viento", ["Patrick Rothfuss"], ["Fantasía", "Aventura"], "Plaza & Janés", 2007, "Español", 78000m, "Relato de formación de un músico y mago marcado por misterio, talento y pérdida."),
        new("Juego de tronos", ["George R. R. Martin"], ["Fantasía", "Política"], "Gigamesh", 1996, "Español", 85000m, "Fantasía política sobre poder, alianzas familiares y amenazas que crecen más allá del trono."),
        new("Las crónicas de Narnia", ["C. S. Lewis"], ["Fantasía", "Juvenil"], "HarperCollins", 1950, "Español", 72000m, "Serie fantástica juvenil sobre mundos paralelos, valentía y dilemas morales."),
        new("La historia interminable", ["Michael Ende"], ["Fantasía", "Juvenil"], "Alfaguara", 1979, "Español", 59000m, "Aventura sobre imaginación, lectura y el vínculo entre un niño y un reino fantástico."),
        new("Terramar", ["Ursula K. Le Guin"], ["Fantasía", "Juvenil"], "Minotauro", 1968, "Español", 64000m, "Fantasía sobre aprendizaje mágico, equilibrio y responsabilidad personal."),
        new("El color de la magia", ["Terry Pratchett"], ["Fantasía", "Aventura"], "Debolsillo", 1983, "Español", 54000m, "Fantasía satírica que juega con viajes, hechicería y convenciones del género."),
        new("Mistborn: El imperio final", ["Brandon Sanderson"], ["Fantasía", "Aventura"], "Ediciones B", 2006, "Español", 72000m, "Fantasía de rebelión, magia metálica y lucha contra un imperio opresivo."),
        new("Dune", ["Frank Herbert"], ["Ciencia ficción", "Política"], "Ace Books", 1965, "Español", 78000m, "Ciencia ficción sobre ecología, religión y poder en un planeta desértico estratégico."),
        new("Fundación", ["Isaac Asimov"], ["Ciencia ficción", "Política"], "Debolsillo", 1951, "Español", 56000m, "Ciclo de ciencia ficción sobre predicción social y preservación del conocimiento."),
        new("1984", ["George Orwell"], ["Distopía", "Política"], "Debolsillo", 1949, "Español", 42000m, "Novela distópica sobre vigilancia, propaganda y manipulación de la verdad."),
        new("Un mundo feliz", ["Aldous Huxley"], ["Distopía", "Sociedad"], "Debolsillo", 1932, "Español", 43000m, "Distopía sobre control social, placer administrado y pérdida de libertad individual."),
        new("Fahrenheit 451", ["Ray Bradbury"], ["Distopía", "Ciencia ficción"], "Debolsillo", 1953, "Español", 44000m, "Novela sobre censura, memoria cultural y resistencia a la destrucción de libros."),
        new("Neuromante", ["William Gibson"], ["Ciencia ficción", "Tecnología"], "Minotauro", 1984, "Español", 62000m, "Ciberpunk sobre redes digitales, crimen y límites entre mente y máquina."),
        new("Solaris", ["Stanisław Lem"], ["Ciencia ficción", "Psicología"], "Impedimenta", 1961, "Español", 64000m, "Ciencia ficción filosófica sobre contacto alienígena y proyecciones de la memoria humana."),
        new("La guerra de los mundos", ["H. G. Wells"], ["Ciencia ficción", "Aventura"], "Penguin Classics", 1898, "Español", 39000m, "Relato pionero de invasión extraterrestre y vulnerabilidad humana."),
        new("¿Sueñan los androides con ovejas eléctricas?", ["Philip K. Dick"], ["Ciencia ficción", "Filosofía"], "Minotauro", 1968, "Español", 58000m, "Novela sobre identidad, empatía y vida artificial en un futuro degradado."),
        new("El problema de los tres cuerpos", ["Cixin Liu"], ["Ciencia ficción", "Ciencia"], "Ediciones B", 2008, "Español", 68000m, "Ciencia ficción sobre contacto extraterrestre, física y consecuencias históricas."),
        new("Hyperion", ["Dan Simmons"], ["Ciencia ficción", "Aventura"], "Ediciones B", 1989, "Español", 79000m, "Relato coral de peregrinación espacial con misterio, religión y tiempo como ejes."),
        new("Y no quedó ninguno", ["Agatha Christie"], ["Misterio", "Thriller"], "Planeta", 1939, "Español", 42000m, "Misterio de encierro donde un grupo de personas enfrenta muertes sucesivas en una isla."),
        new("El asesinato de Roger Ackroyd", ["Agatha Christie"], ["Misterio", "Thriller"], "Planeta", 1926, "Español", 41000m, "Caso detectivesco que explora testimonio, sospecha y estructura narrativa."),
        new("El sabueso de los Baskerville", ["Arthur Conan Doyle"], ["Misterio", "Terror"], "Alianza Editorial", 1902, "Español", 39000m, "Investigación de Sherlock Holmes con atmósfera gótica y leyenda familiar."),
        new("Drácula", ["Bram Stoker"], ["Terror", "Literatura clásica"], "Penguin Classics", 1897, "Español", 45000m, "Novela gótica sobre vampirismo, deseo, miedo y modernidad."),
        new("Frankenstein", ["Mary Shelley"], ["Terror", "Ciencia ficción"], "Penguin Classics", 1818, "Español", 43000m, "Historia sobre creación, responsabilidad científica y rechazo social."),
        new("El resplandor", ["Stephen King"], ["Terror", "Psicología"], "Debolsillo", 1977, "Español", 62000m, "Terror psicológico sobre aislamiento familiar y una presencia inquietante en un hotel."),
        new("El silencio de los corderos", ["Thomas Harris"], ["Thriller", "Psicología"], "Debolsillo", 1988, "Español", 59000m, "Thriller criminal sobre investigación, manipulación psicológica y violencia serial."),
        new("El nombre de la rosa", ["Umberto Eco"], ["Misterio", "Historia"], "Debolsillo", 1980, "Español", 65000m, "Misterio histórico ambientado en una abadía medieval atravesada por disputas intelectuales."),
        new("Perdida", ["Gillian Flynn"], ["Thriller", "Psicología"], "Penguin Random House", 2012, "Español", 58000m, "Thriller doméstico sobre apariencia pública, matrimonio y manipulación narrativa."),
        new("La chica del tren", ["Paula Hawkins"], ["Thriller", "Misterio"], "Planeta", 2015, "Español", 56000m, "Suspenso contemporáneo sobre memoria, observación y una desaparición investigada desde la duda."),
        new("La República", ["Platón"], ["Filosofía", "Política"], "Alianza Editorial", null, "Español", 42000m, "Diálogo filosófico sobre justicia, educación, gobierno y organización de la ciudad."),
        new("Ética a Nicómaco", ["Aristóteles"], ["Filosofía", "Educación"], "Alianza Editorial", null, "Español", 42000m, "Tratado sobre virtud, felicidad y formación del carácter."),
        new("Meditaciones", ["Marco Aurelio"], ["Filosofía", "Desarrollo personal"], "Penguin Classics", null, "Español", 36000m, "Reflexiones estoicas sobre disciplina interior, deber y aceptación."),
        new("El príncipe", ["Nicolás Maquiavelo"], ["Filosofía", "Política"], "Alianza Editorial", 1532, "Español", 35000m, "Ensayo político sobre poder, estrategia y conservación del gobierno."),
        new("Así habló Zaratustra", ["Friedrich Nietzsche"], ["Filosofía", "Ensayo"], "Alianza Editorial", 1883, "Español", 48000m, "Obra filosófica y poética sobre valores, transformación y crítica moral."),
        new("El mundo de Sofía", ["Jostein Gaarder"], ["Filosofía", "Educación"], "Siruela", 1991, "Español", 52000m, "Novela de aprendizaje que introduce grandes preguntas e ideas de la historia de la filosofía."),
        new("El arte de la guerra", ["Sun Tzu"], ["Filosofía", "Política"], "Austral", null, "Español", 32000m, "Texto estratégico sobre conflicto, planificación y lectura del contexto."),
        new("El extranjero", ["Albert Camus"], ["Filosofía", "Novela contemporánea"], "Alianza Editorial", 1942, "Español", 41000m, "Novela breve sobre absurdo, indiferencia social y juicio moral."),
        new("Sapiens", ["Yuval Noah Harari"], ["Historia", "Sociedad"], "Debate", 2011, "Español", 69000m, "Panorama histórico sobre evolución humana, cultura y construcción de sociedades complejas."),
        new("Homo Deus", ["Yuval Noah Harari"], ["Historia", "Tecnología"], "Debate", 2015, "Español", 72000m, "Ensayo sobre posibles futuros humanos atravesados por datos, biotecnología y poder."),
        new("Una breve historia del tiempo", ["Stephen Hawking"], ["Ciencia", "Educación"], "Planeta", 1988, "Español", 58000m, "Introducción divulgativa a cosmología, agujeros negros y preguntas sobre el universo."),
        new("El diario de Ana Frank", ["Ana Frank"], ["Biografía", "Historia"], "Debolsillo", 1947, "Español", 42000m, "Testimonio personal sobre adolescencia, persecución y vida oculta durante la Segunda Guerra Mundial."),
        new("Los hombres me explican cosas", ["Rebecca Solnit"], ["Feminismo", "Ensayo"], "Capitán Swing", 2014, "Español", 49000m, "Ensayos sobre género, autoridad y formas cotidianas de silenciamiento."),
        new("El segundo sexo", ["Simone de Beauvoir"], ["Feminismo", "Filosofía"], "Cátedra", 1949, "Español", 78000m, "Ensayo fundamental sobre construcción social de la mujer, libertad y desigualdad."),
        new("Breve historia de casi todo", ["Bill Bryson"], ["Ciencia", "Historia"], "RBA", 2003, "Español", 65000m, "Divulgación científica sobre origen del universo, Tierra, vida y conocimiento moderno."),
        new("Armas, gérmenes y acero", ["Jared Diamond"], ["Historia", "Sociedad"], "Debate", 1997, "Español", 74000m, "Ensayo histórico sobre geografía, tecnología y desigualdad entre sociedades."),
        new("Pensar rápido, pensar despacio", ["Daniel Kahneman"], ["Psicología", "Ensayo"], "Debate", 2011, "Español", 74000m, "Exploración de sesgos cognitivos y dos modos de tomar decisiones."),
        new("Hábitos atómicos", ["James Clear"], ["Desarrollo personal", "Psicología"], "Diana", 2018, "Español", 69000m, "Guía práctica sobre cambios pequeños, sistemas personales y construcción de hábitos."),
        new("El hombre en busca de sentido", ["Viktor Frankl"], ["Psicología", "Biografía"], "Herder", 1946, "Español", 43000m, "Reflexión sobre sufrimiento, libertad interior y búsqueda de sentido."),
        new("Inteligencia emocional", ["Daniel Goleman"], ["Psicología", "Desarrollo personal"], "Kairós", 1995, "Español", 59000m, "Ensayo divulgativo sobre emociones, autoconocimiento y habilidades sociales."),
        new("Los 7 hábitos de la gente altamente efectiva", ["Stephen R. Covey"], ["Desarrollo personal", "Educación"], "Paidós", 1989, "Español", 67000m, "Modelo de liderazgo personal basado en principios, hábitos y responsabilidad."),
        new("Mindset", ["Carol S. Dweck"], ["Psicología", "Educación"], "Sirio", 2006, "Español", 59000m, "Ensayo sobre mentalidad de crecimiento, aprendizaje y respuesta al error."),
        new("Flow", ["Mihály Csíkszentmihályi"], ["Psicología", "Desarrollo personal"], "Kairós", 1990, "Español", 62000m, "Estudio sobre concentración, experiencia óptima y motivación en actividades significativas."),
        new("Clean Code", ["Robert C. Martin"], ["Programación", "Ingeniería de software"], "Prentice Hall", 2008, "Inglés", 210000m, "Guía técnica sobre escritura de código claro, mantenible y orientado a intención."),
        new("The Pragmatic Programmer", ["Andrew Hunt", "David Thomas"], ["Programación", "Ingeniería de software"], "Addison-Wesley", 1999, "Inglés", 185000m, "Libro práctico sobre criterio profesional, herramientas y hábitos de desarrollo de software."),
        new("Design Patterns", ["Erich Gamma", "Richard Helm", "Ralph Johnson", "John Vlissides"], ["Ingeniería de software", "Arquitectura de software"], "Addison-Wesley", 1994, "Inglés", 260000m, "Catálogo clásico de patrones para resolver problemas recurrentes de diseño orientado a objetos."),
        new("Refactoring", ["Martin Fowler"], ["Ingeniería de software", "Programación"], "Addison-Wesley", 1999, "Inglés", 235000m, "Guía para mejorar diseño interno de código sin cambiar su comportamiento observable."),
        new("Domain-Driven Design", ["Eric Evans"], ["Arquitectura de software", "Ingeniería de software"], "Addison-Wesley", 2003, "Inglés", 280000m, "Enfoque para modelar software complejo alrededor del lenguaje y reglas del negocio."),
        new("Clean Architecture", ["Robert C. Martin"], ["Arquitectura de software", "Ingeniería de software"], "Prentice Hall", 2017, "Inglés", 230000m, "Principios para organizar sistemas mantenibles, testeables y desacoplados."),
        new("Code Complete", ["Steve McConnell"], ["Programación", "Ingeniería de software"], "Microsoft Press", 1993, "Inglés", 250000m, "Manual amplio sobre construcción de software, estilo, pruebas y disciplina técnica."),
        new("Introduction to Algorithms", ["Thomas H. Cormen", "Charles E. Leiserson", "Ronald L. Rivest", "Clifford Stein"], ["Algoritmos", "Programación"], "MIT Press", 1990, "Inglés", 360000m, "Texto académico sobre diseño, análisis y aplicación de algoritmos fundamentales."),
        new("Structure and Interpretation of Computer Programs", ["Harold Abelson", "Gerald Jay Sussman"], ["Programación", "Educación"], "MIT Press", 1985, "Inglés", 190000m, "Introducción profunda a abstracción, interpretación y estructura de programas."),
        new("Designing Data-Intensive Applications", ["Martin Kleppmann"], ["Ingeniería de software", "Tecnología"], "O'Reilly Media", 2017, "Inglés", 290000m, "Estudio de sistemas de datos, consistencia, almacenamiento y arquitecturas distribuidas."),
        new("El principito", ["Antoine de Saint-Exupéry"], ["Infantil", "Filosofía"], "Salamandra", 1943, "Español", 36000m, "Fábula poética sobre amistad, mirada infantil y sentido de lo esencial."),
        new("Matilda", ["Roald Dahl"], ["Infantil", "Juvenil"], "Alfaguara", 1988, "Español", 42000m, "Historia de una niña lectora con ingenio frente a adultos autoritarios."),
        new("Charlie y la fábrica de chocolate", ["Roald Dahl"], ["Infantil", "Aventura"], "Alfaguara", 1964, "Español", 43000m, "Aventura infantil sobre imaginación, familia y una fábrica llena de sorpresas."),
        new("Alicia en el país de las maravillas", ["Lewis Carroll"], ["Infantil", "Fantasía"], "Penguin Classics", 1865, "Español", 39000m, "Viaje fantástico por un mundo de lógica absurda, juegos de lenguaje y curiosidad."),
        new("La telaraña de Charlotte", ["E. B. White"], ["Infantil", "Educación"], "HarperCollins", 1952, "Español", 41000m, "Historia infantil sobre amistad, cuidado y el valor de una vida sencilla."),
        new("Donde viven los monstruos", ["Maurice Sendak"], ["Infantil", "Fantasía"], "HarperCollins", 1963, "Español", 38000m, "Álbum infantil sobre imaginación, enojo y regreso al afecto familiar."),
        new("El maravilloso mago de Oz", ["L. Frank Baum"], ["Infantil", "Aventura"], "Penguin Classics", 1900, "Español", 39000m, "Aventura fantástica sobre viaje, amistad y deseo de volver a casa."),
        new("Anne de las Tejas Verdes", ["L. M. Montgomery"], ["Juvenil", "Novela contemporánea"], "Alfaguara", 1908, "Español", 47000m, "Novela juvenil sobre imaginación, pertenencia y crecimiento en una comunidad rural."),
        new("La isla del tesoro", ["Robert Louis Stevenson"], ["Juvenil", "Aventura"], "Austral", 1883, "Español", 41000m, "Aventura clásica de piratas, mapas secretos y aprendizaje frente al peligro."),
        new("Mujercitas", ["Louisa May Alcott"], ["Juvenil", "Literatura clásica"], "Penguin Classics", 1868, "Español", 48000m, "Historia familiar sobre crecimiento, afecto, vocación y decisiones de cuatro hermanas.")
    ];

    public static IReadOnlyCollection<string> Authors { get; } = Books
        .SelectMany(book => book.Authors)
        .Distinct(StringComparer.OrdinalIgnoreCase)
        .OrderBy(author => author)
        .ToArray();
}

public sealed record RealCatalogBookSeed(
    string Title,
    IReadOnlyCollection<string> Authors,
    IReadOnlyCollection<string> Categories,
    string? Publisher,
    int? PublicationYear,
    string Language,
    decimal Price,
    string Description);
